### ISSUE TITLE
Chest is invisible and empty

### ISSUE THREAD

**Issue by PetteriM1** [larryTheCoder/ASkyBlock-Nukkit#26]
When i go to my island first time chest is invisible. When I go back to spawn, go to other word and come bac to my island chest is visible but empty.

**Comment by larryTheCoder** [comment]
Confirmed @PetteriM1 
Picture
![Bugs](https://cdn.discordapp.com/attachments/345183951897362438/345186744095735808/unknown.png)

**Comment by larryTheCoder** [comment]
@PetteriM1 69cc91f37635de8b1001daaa38abd43e0aad7d95 fixed this problem.

**Comment by PetteriM1** [comment]
It works!

**Comment by PetteriM1** [comment]
But in chest there is sign at lava place and in front of chest.

**Comment by PetteriM1** [comment]
![image](https://user-images.githubusercontent.com/26197131/29220861-1c0ff34a-7ec5-11e7-8dde-80e23f6d9201.JPG)
Always same items

**Comment by larryTheCoder** [comment]
@PetteriM1 The items are provided by schematic you can get a list of all the goods at [Minecraft Schematic](http://www.minecraft-schematics.com/) website

**Comment by larryTheCoder** [comment]
@PetteriM1 is the sign should be placed with lava?
Also can you take items in the chest?

**Comment by PetteriM1** [comment]
I can't take items from chest.

**Comment by PetteriM1** [comment]
And the chest was invisible before I teleported to other world and back.

**Comment by larryTheCoder** [comment]
@PetteriM1 Chest not visible because the chest is delaying 5 secs to spawn them
Can you reproduce what items that cannot been taken. I cant take all items in the chest

**Comment by PetteriM1** [comment]
I can take ice, cactus and melon.

**Comment by PetteriM1** [comment]
And why sign in front of chest?

**Comment by PetteriM1** [comment]
![image](https://user-images.githubusercontent.com/26197131/29243009-13e4d526-7f9e-11e7-812e-0e178750efce.JPG)
What this mean? Is it possible to change chest items in config?

**Comment by larryTheCoder** [comment]
Please be informed that your island were generated by using .schematic in skyblock absolute folder. But I added some layer changes that will change every items in chest by using `shouldOverride` in `config.yml`
```yaml
   items:
     # The usage of this function are to perform that chest's in the schematic
     # Will be replaced with this items
     #
     # If the chest empty, it will use your chest items as items in the chest.
     shouldOverride: false
     # Items that will be in the chest when the player starts an island
     # Must be in Nukkit Item format. Format is <ID>:<Qty> or <ID>:<Data>:<Qty>
     # Use <Data> to set the durability of a item or to select sub-items/colors.  
     #
     # Spawn EGGs is not available yet! do not put I warned you :P
     #
     # Check console for errors and guidance after reloading configuration
     chestItems: 'ICE:2 MELON:1 TORCH:2 BONE:1 LAVA_BUCKET:1 PUMPKIN_SEEDS:1 SUGAR_CANE:1 RED_MUSHROOM:1 BROWN_MUSHROOM:1 CACTUS:1 BREAD:1 WHEAT:1 LEATHER_BOOTS:1 LEATHER_HELMET:1 LEATHER_CHESTPLATE:1 LEATHER_LEGGINGS:1'
```
